In [1]:
print("Hellow words")

Hellow words


In [2]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [3]:
a="shanker pande"
print(a)
print(len(a))
print(type(a))
print("String?",isinstance(a,int))

shanker pande
13
<class 'str'>
String? False


In [4]:
a[2]
a[4]
a[:]
a[2:7]
a[-1]
a[::-1]

'ednap reknahs'

In [5]:
b="I am data sciensts"
print(b)
print(len(b))
print(type(b))
print(b[::-1])
b=b.replace("data sciensts","web devoper")
print(b)
b=b.replace("web devoper","Mechanical Engineering")
print(b)
b=b.replace("Mechanical Engineering","data sciensts")
print(b)

I am data sciensts
18
<class 'str'>
stsneics atad ma I
I am web devoper
I am Mechanical Engineering
I am data sciensts


In [6]:
a="I am data scientict"
b="I am web devoper"
c="I am Software Engineer"
d=a+b+c
print(d)

I am data scientictI am web devoperI am Software Engineer


In [7]:
"I am data scientict" in a

True

In [8]:
"I am web devoper" in b

True

In [9]:
print(2*2)

4


In [10]:
a.partition("data")

('I am ', 'data', ' scientict')

In [11]:
b.partition("devoper")

('I am web ', 'devoper', '')

In [12]:
q="  i am abhishek i am from aurangabd i have complited my education in marathi medium "

In [13]:
q.partition("aurangabd")

('  i am abhishek i am from ',
 'aurangabd',
 ' i have complited my education in marathi medium ')

In [14]:
q.count("e")

5

In [15]:
q.count("a")

10

In [16]:
q.count("s")

1

In [17]:
q.split()

['i',
 'am',
 'abhishek',
 'i',
 'am',
 'from',
 'aurangabd',
 'i',
 'have',
 'complited',
 'my',
 'education',
 'in',
 'marathi',
 'medium']

In [18]:
s=" abhishek"

In [19]:
s.lstrip()

'abhishek'

In [20]:
s="abhishek  "

In [21]:
s.rstrip()

'abhishek'

In [22]:
s="Hi There open your demate account"

In [23]:
s.split()

['Hi', 'There', 'open', 'your', 'demate', 'account']

In [24]:
s.lower()

'hi there open your demate account'

In [25]:
s.upper()

'HI THERE OPEN YOUR DEMATE ACCOUNT'

In [26]:
q.upper()

'  I AM ABHISHEK I AM FROM AURANGABD I HAVE COMPLITED MY EDUCATION IN MARATHI MEDIUM '

In [27]:
q.lower()

'  i am abhishek i am from aurangabd i have complited my education in marathi medium '

In [28]:
s="suresh"
r="shanker"
print(s,r)
"suresh" in s

suresh shanker


True

In [29]:
s.startswith("su")
s.startswith("ka")
r.startswith("shank")

True

In [30]:
r.startswith("ll")
r.startswith("kaka")
r.startswith("shanker")

True

In [31]:
r.endswith("er")
r.endswith("f")
r.endswith("r")
r.endswith("ker")

True

In [32]:
a=input()

kkk


In [33]:
x=int(4.111)
print(type(x))
y=float(7)
print(type(y))
z=str(85)
print(type(z))
n=bool(4)
print(type(n))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [34]:
a,b,c="ABhishek","shnaker","anirudh"
print(a,b,c)

ABhishek shnaker anirudh


In [35]:
a=23
b="my name is abhishek and my age is {}"
print(b.format(a))

my name is abhishek and my age is 23


In [36]:
a="my laptop name ASUS and their price is {}"
b=45000
print(a.format(b))

my laptop name ASUS and their price is 45000


In [37]:
a="my room number is {}"
b=12
print(a.format(b))

my room number is 12


In [38]:
a="my mobile price is {}"
b=12000
print(a.format(b))

my mobile price is 12000


In [39]:
a="my name abhishek i am living in {} my laptop name {}"
b="AURANGABAD"
c="AUSUS"
print(a.format(b,c))


my name abhishek i am living in AURANGABAD my laptop name AUSUS


In [40]:
a=3+3
a=5-3
a=5*5
a=5/2
a=5**5
a==1
a

3125

In [41]:
w="abhi"
print(w)

abhi


In [42]:
a=20>22 and 20>12
a=20>12 and 33<77
a= len("abhi")>len("dd") and len("dighule")<len("s")
a= len("ABHISHEK") >len("abhi") or len("anirudh") <len("abhi")
a

True

In [43]:
a=10>9
print(a)
a=10<1
print(a)
a=10>=10
print(a)
a=10<=1
print(a)
a=2==2
print(a)
a= 4!=4
print(a)

True
False
True
False
True
False


In [44]:
import datetime
x=datetime.datetime.now()
print(x)

2024-01-31 19:01:56.710061


In [45]:
print(x.year)
print(x.month)
print(x.day)
print(x.second)
print(x.microsecond)
print(x.strftime("%A"))
print(x.strftime("%B"))
print(x.strftime("%C"))
print(x.strftime("%f"))
print(x.strftime("%D"))
print(x.strftime("%F"))
print(x.strftime("%X"))

2024
1
31
56
710061
Wednesday
January
20
710061
01/31/24
2024-01-31
19:01:56


In [46]:
a=10
b=20
if a>b:
    print("it is true")
else:
    print("it is negetive")

it is negetive


In [47]:
a=22
b=19
if a>b:
    print("it is true")
else:
    print("it is negective")

it is true


In [48]:
a=23
b=55
if a>b:
    print("it is true")
if a>=b:
    print("it is equel")
else:
    print("a is not statisfied")

a is not statisfied


In [49]:
a=24
b=33
if a>b:
    print("a is grether than b")
if a<b:
    print("a is less than b")
if a>=b:
    print("a is grether than and equel")
if a<=b:
    print("a is less than b")
if a==b:
    print("a is equel to equel b")
if a>b and a<b:
    print("right")
if a>b or a<b:
    print("a is grethet than b and a is less than b")
else:
    print("all worng")

a is less than b
a is less than b
a is grethet than b and a is less than b


In [50]:
handsome="true"
salary="true"
if handsome=="true" and salary=="fslse":
    print("you will not marray")
if handsome=="true" and salary=="true":
    print("you are suitable candidant")
else:
    print("bagvon barose")

you are suitable candidant


In [51]:
age=int(input("enter your age: "))
if age>18:
    print("you can apply for licence")
else:
    print("itni jaldi kya hai")

enter your age: 55
you can apply for licence


In [52]:
i=2
while i<9:
    i+=2
    print(i)

4
6
8
10


In [53]:
i=1
while i<9:
    i+=1
    if(i==7):
        break
    print(i)

2
3
4
5
6


In [54]:
i=10
while i<20:
    i+=1
    if(i==15):
        continue
    print(i)

11
12
13
14
16
17
18
19
20


In [55]:
i=11
while i<33:
    i+=1
    if(i==19):
        continue
    print(i)
else:
    print("11 is not grether than 33")

12
13
14
15
16
17
18
20
21
22
23
24
25
26
27
28
29
30
31
32
33
11 is not grether than 33


In [56]:
stuff="Abhishek"
for i in stuff:
    print(i)

A
b
h
i
s
h
e
k


In [57]:
fruits=["Apple","Banana","Pineple","chery","mango"]

In [58]:
for i in fruits:
    print(i)

Apple
Banana
Pineple
chery
mango


In [59]:
for i in fruits:
    if (i=="chery"):
        break
    print(i)

Apple
Banana
Pineple


In [60]:
for i in fruits:
    if(i=="chery"):
        continue
    print(i)

Apple
Banana
Pineple
mango


In [61]:
gruup1=["Abhishek","shanker","aniket","anirudhh","rutik"]
group2=["pavan","rohit","anan","neru","baba"]
for x in gruup1:
    for r in group2:
        print(x,r)

Abhishek pavan
Abhishek rohit
Abhishek anan
Abhishek neru
Abhishek baba
shanker pavan
shanker rohit
shanker anan
shanker neru
shanker baba
aniket pavan
aniket rohit
aniket anan
aniket neru
aniket baba
anirudhh pavan
anirudhh rohit
anirudhh anan
anirudhh neru
anirudhh baba
rutik pavan
rutik rohit
rutik anan
rutik neru
rutik baba


In [62]:
x=gruup1+group2
x

['Abhishek',
 'shanker',
 'aniket',
 'anirudhh',
 'rutik',
 'pavan',
 'rohit',
 'anan',
 'neru',
 'baba']

In [63]:
for i in "ABHISHEK DIGHULE":
    print(i)

A
B
H
I
S
H
E
K
 
D
I
G
H
U
L
E


In [64]:
city=["Aurangabed","Hydrabad","banglore","chanai","mumbai"]
for i in city:
    print(i)

Aurangabed
Hydrabad
banglore
chanai
mumbai


In [65]:
for i in city:
    if(i=="Hydrabad"):
        continue
    if (i=="banglore"):
        continue
    print(i)
else:
    print("finally rechead")

Aurangabed
chanai
mumbai
finally rechead


In [66]:
for i in city:
    if(i=="mumbai"):
        break
    print(i)

Aurangabed
Hydrabad
banglore
chanai


In [67]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [68]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [69]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [70]:
s="abhishek"
a=2
a1=True
print(type(s))
print(type(a))
print(type(a1))
len(s)

<class 'str'>
<class 'int'>
<class 'bool'>


8

In [71]:
a,v,s="abhisjelk","suredh",'d'
print(a)
print(v)
print(s)

abhisjelk
suredh
d


In [72]:
a[3:]

'isjelk'

In [73]:
a="my mobile name is noika"
print(a)
print(type(a))
print(len(a))

my mobile name is noika
<class 'str'>
23


In [74]:
a.replace("noika","samsung")

'my mobile name is samsung'

In [75]:
a=a.count("ss")
print(a)

0


In [76]:
s="my name is abhishek"

In [77]:
s.partition("abhishek")

('my name is ', 'abhishek', '')

In [78]:
s.split()

['my', 'name', 'is', 'abhishek']

In [79]:
s.strip()
s.lstrip()
s.rstrip()

'my name is abhishek'

In [80]:
"abhishek" in s

True

In [81]:
s.upper()

'MY NAME IS ABHISHEK'

In [82]:
s.lower()

'my name is abhishek'

In [83]:
s.startswith("a")

False

In [84]:
s.startswith("my")

True

In [85]:
s.endswith("ek")

True

In [86]:
s=int(input("Age:"))

Age:44


In [87]:
a= 10<11 and 10>22
print(a)

False


In [88]:
a=10>9 and 11<=11
print(a)

True


In [89]:
a= 10<11 or 10>22
print(a)

True


In [90]:
a= not(10<11 or 10>22)
print(a)

False


In [91]:
import datetime
x=datetime.datetime.now()
print(x)
print(x.year)
print(x.day)
print(x.month)
print(x.strftime("%A"))

2024-01-31 19:02:07.545910
2024
31
1
Wednesday


In [92]:
a=10
b=13
if a<b:
    print("a is lessthen b")

a is lessthen b


In [93]:
a=4
b=9
if a>b:
    print("a is gretherthen b")
else:
    print("wrong number")

wrong number


In [94]:
a=20
b=12
if a<b and a>b:
    print("hard")
else:
    print("aaa")

aaa


In [95]:
a=20
b=12
if a<b or a>b:
    print("hard")
else:
    print("aaa")

hard


In [96]:
a=20
b=12
if not(a<b and a>b):
    print("hard")
else:
    print("aaa")

hard


In [97]:
a=10
while a<19:
    if(a==13):
        break
    a+=1
    print(a)
else:
    print("abhishek")

11
12
13


In [98]:
for i in city:
    print(i)

Aurangabed
Hydrabad
banglore
chanai
mumbai


In [99]:
for i in city:
    if (i=="chanai"):
        break
    print(i)

Aurangabed
Hydrabad
banglore


In [100]:
for i in city:
    if (i=="chanai"):
        continue
    print(i)

Aurangabed
Hydrabad
banglore
mumbai


In [101]:
for i in gruup1:
    for x in group2:
        print(i,x)

Abhishek pavan
Abhishek rohit
Abhishek anan
Abhishek neru
Abhishek baba
shanker pavan
shanker rohit
shanker anan
shanker neru
shanker baba
aniket pavan
aniket rohit
aniket anan
aniket neru
aniket baba
anirudhh pavan
anirudhh rohit
anirudhh anan
anirudhh neru
anirudhh baba
rutik pavan
rutik rohit
rutik anan
rutik neru
rutik baba


In [102]:
"pavan" in group2

True

In [103]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


# LIST

In [104]:
thelist=["Abhishek","Shnaker","Abhishek","Anirudh","Aniket","hardhal"]#chnageble #duplictes allowed #order
l=list(("mama","kaka"))
print(thelist)
print(type(thelist))
print(len(thelist))
print(type(l))
print(len(l))

['Abhishek', 'Shnaker', 'Abhishek', 'Anirudh', 'Aniket', 'hardhal']
<class 'list'>
6
<class 'list'>
2


In [105]:
thelist.count("Abhishek")

2

In [106]:
thelist.index("Anirudh")

3

In [107]:
#indexing
thelist[1]
thelist[-3]
thelist[::-1]
thelist[::2]
thelist[1:3]

['Shnaker', 'Abhishek']

In [108]:
thelist[1]="SHANKER"
thelist[0]="ABHISHEK"
thelist[2]="ANIRUDH"
thelist[3]="ANIKET"

thelist[4:5]=["HARSHAL","MONOJ"]
thelist.insert(6,"SURESH")
print(thelist)

['ABHISHEK', 'SHANKER', 'ANIRUDH', 'ANIKET', 'HARSHAL', 'MONOJ', 'SURESH', 'hardhal']


In [109]:
"ABHISHEK" in thelist

True

In [110]:
if "ABHISHEK" in thelist:
    print("WOW")
else:
    print("Bad")

WOW


In [111]:
thelist.append("gajanan")

In [112]:
thelist

['ABHISHEK',
 'SHANKER',
 'ANIRUDH',
 'ANIKET',
 'HARSHAL',
 'MONOJ',
 'SURESH',
 'hardhal',
 'gajanan']

In [113]:
thelist.remove("gajanan")

In [114]:
thelist.pop(4)

'HARSHAL'

In [115]:
thelist

['ABHISHEK', 'SHANKER', 'ANIRUDH', 'ANIKET', 'MONOJ', 'SURESH', 'hardhal']

In [116]:
del thelist[3]

In [117]:
thelist.clear()

In [118]:
thelist

[]

In [119]:
Name=["ROHIT","SHNAKER","ANIRUDH","ABHISHEK","ANIKET"]
laptop=["HP","ASUS","NO","ASUS","NO"]

In [120]:
Name.extend(laptop)
Name

['ROHIT',
 'SHNAKER',
 'ANIRUDH',
 'ABHISHEK',
 'ANIKET',
 'HP',
 'ASUS',
 'NO',
 'ASUS',
 'NO']

In [121]:
info= Name+laptop
info

['ROHIT',
 'SHNAKER',
 'ANIRUDH',
 'ABHISHEK',
 'ANIKET',
 'HP',
 'ASUS',
 'NO',
 'ASUS',
 'NO',
 'HP',
 'ASUS',
 'NO',
 'ASUS',
 'NO']

In [122]:
for i in Name:
    print(i)

ROHIT
SHNAKER
ANIRUDH
ABHISHEK
ANIKET
HP
ASUS
NO
ASUS
NO


In [123]:
for i in range(len(Name)):
    print(Name[i])

ROHIT
SHNAKER
ANIRUDH
ABHISHEK
ANIKET
HP
ASUS
NO
ASUS
NO


In [124]:
i=0
while i<len(Name):
    print(Name[i])
    i+=1

ROHIT
SHNAKER
ANIRUDH
ABHISHEK
ANIKET
HP
ASUS
NO
ASUS
NO


In [125]:
[print (i) for i in Name]

ROHIT
SHNAKER
ANIRUDH
ABHISHEK
ANIKET
HP
ASUS
NO
ASUS
NO


[None, None, None, None, None, None, None, None, None, None]

In [1]:
mobile=["Redmi","Oppo","Vivo","Xiomi","Sumsung","Nokia","Motorola"]
newlist=[]
for i in mobile:
    if "o" in i:
        newlist.append(i)
print(newlist)
        

['Oppo', 'Vivo', 'Xiomi', 'Nokia', 'Motorola']


In [127]:
nwelist=[]
for i in mobile:
    if "a" in i:
        nwelist.append(i)
print(nwelist)

['Nokia', 'Motorola']


In [128]:
[i for i in mobile if "a" in i]

['Nokia', 'Motorola']

In [129]:
[i.upper() for i in mobile ]

['REDMI', 'OPPO', 'VIVO', 'XIOMI', 'SUMSUNG', 'NOKIA', 'MOTOROLA']

In [71]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]#comprehention list
vowels = "aeiou" # A string containing all the vowels
vowels_from_words1 = [c for i in words1 for c in i if c in "aeiou"]
print(vowels_from_words1)

['a', 'e', 'a', 'a', 'a', 'e', 'o', 'a', 'e', 'e', 'o']


In [72]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
vowels = "aeiou" # A string containing all the vowels
vowels_from_words1 = [c for i in words1 for c in i if c in "aeiou"]
print(vowels_from_words1)

['a', 'e', 'a', 'a', 'a', 'e', 'o', 'a', 'e', 'e', 'o']


In [130]:
mobile.sort()
mobile

['Motorola', 'Nokia', 'Oppo', 'Redmi', 'Sumsung', 'Vivo', 'Xiomi']

In [131]:
mobile.reverse()
mobile

['Xiomi', 'Vivo', 'Sumsung', 'Redmi', 'Oppo', 'Nokia', 'Motorola']

In [132]:
mobile.sort(key=str.lower)

In [133]:
mobile

['Motorola', 'Nokia', 'Oppo', 'Redmi', 'Sumsung', 'Vivo', 'Xiomi']

In [134]:
a=[2,5,3,9,5,7,8,3,5]
a.sort()
a

[2, 3, 3, 5, 5, 5, 7, 8, 9]

In [135]:
a.reverse()
a

[9, 8, 7, 5, 5, 5, 3, 3, 2]

# Tuple

In [136]:
mylist=("abhishek","suresh","aniket","savita","vitthal","sadhana")
print(mylist)
o=tuple(("data","mama"))
print(o)
print(type(mylist))
print(len(mylist))

('abhishek', 'suresh', 'aniket', 'savita', 'vitthal', 'sadhana')
('data', 'mama')
<class 'tuple'>
6


In [137]:
mylist[2]
mylist[2:5]

('aniket', 'savita', 'vitthal')

In [138]:
k=list(mylist)
k.append("damodhar")
mylist=tuple(k)
mylist=list(mylist)
mylist.append("Yash")
mylist=tuple(mylist)
mylist

('abhishek',
 'suresh',
 'aniket',
 'savita',
 'vitthal',
 'sadhana',
 'damodhar',
 'Yash')

In [139]:
mylist=list(mylist)
mylist[1]="DIGHULE"
mylist=tuple(mylist)
mylist

('abhishek',
 'DIGHULE',
 'aniket',
 'savita',
 'vitthal',
 'sadhana',
 'damodhar',
 'Yash')

In [140]:
"DIGHULE" in mylist

True

In [141]:
if "DIGHULE" in mylist:
    print("It is true")
else:
    print("It is not true")

It is true


In [142]:
mylist=list(mylist)
mylist.remove("Yash")
mylist=tuple(mylist)
mylist

('abhishek', 'DIGHULE', 'aniket', 'savita', 'vitthal', 'sadhana', 'damodhar')

In [143]:
mylist=list(mylist)
mylist.insert(1,"AMIT")
mylist=tuple(mylist)
mylist=list(mylist)
mylist.pop(1)
mylist=tuple(mylist)
mylist


('abhishek', 'DIGHULE', 'aniket', 'savita', 'vitthal', 'sadhana', 'damodhar')

In [144]:
city=("Aurangabd","Banglore","chanai","pune","mumbai")

In [145]:
for i in city:
    print(i.lower())

aurangabd
banglore
chanai
pune
mumbai


In [146]:
i=0
while i<len(city):
    print(i)
    i+=1

0
1
2
3
4


In [147]:
for i in mylist:
    print(i)

abhishek
DIGHULE
aniket
savita
vitthal
sadhana
damodhar


In [148]:
for i in range(len(city)):
    print(city[i])

Aurangabd
Banglore
chanai
pune
mumbai


In [149]:
city=list(city)
new=[]
for i in city:
    if "a" in i:
        new.append(i)
print(new)
new=tuple(new)
print(new)

['Aurangabd', 'Banglore', 'chanai', 'mumbai']
('Aurangabd', 'Banglore', 'chanai', 'mumbai')


In [150]:
[print(i) for i in city if "a" in i]

Aurangabd
Banglore
chanai
mumbai


[None, None, None, None]

In [151]:
[i.upper() for x in city]

['MUMBAI', 'MUMBAI', 'MUMBAI', 'MUMBAI', 'MUMBAI']

In [123]:
a=[4,12,35,36,90,44,63,28]
maxwell = [x for x in a if x > 45] # Using list comprehension
print(maxwell)

[90, 63]


In [152]:
[i.lower() for x in city]

['mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai']

In [153]:
mylist=list(mylist)
mylist.sort()
mylist=tuple(mylist)
mylist

('DIGHULE', 'abhishek', 'aniket', 'damodhar', 'sadhana', 'savita', 'vitthal')

In [154]:
mylist=list(mylist)
mylist.reverse()
mylist=tuple(mylist)
mylist

('vitthal', 'savita', 'sadhana', 'damodhar', 'aniket', 'abhishek', 'DIGHULE')

In [155]:
mylist=list(mylist)
mylist.sort(key=str.lower)
mylist=tuple(mylist)
mylist

('abhishek', 'aniket', 'damodhar', 'DIGHULE', 'sadhana', 'savita', 'vitthal')

In [156]:
[i.upper() for i in mylist]

['ABHISHEK', 'ANIKET', 'DAMODHAR', 'DIGHULE', 'SADHANA', 'SAVITA', 'VITTHAL']

In [157]:
capital=[]
for i in mylist:
    capital.append(i.upper())
print(capital)

['ABHISHEK', 'ANIKET', 'DAMODHAR', 'DIGHULE', 'SADHANA', 'SAVITA', 'VITTHAL']


In [158]:
typle1=("Mubai","aurangabad")
tuple2=("pune","bangolore")
print(type(typle1))

<class 'tuple'>


In [159]:
tuple3=typle1+tuple2
tuple3

('Mubai', 'aurangabad', 'pune', 'bangolore')

In [160]:
typle1=list(typle1)
typle1.clear()
typle1=tuple(typle1)
typle1

()

In [161]:
r=list(typle1)
g=list(tuple2)
r.extend(g)
typle1=tuple(r)
tuple2=tuple(g)
print(typle1)

('pune', 'bangolore')


In [162]:
mytuple1 = ("Hero Honda", "Maruti", "spender", "bajaj", "activa", "vivPA")
newer=[]
tata=list(mytuple1)
for i in tata:
    if "a" in i:
        newer.append(i)
        abhi=tuple(newer)
print(abhi)

('Hero Honda', 'Maruti', 'bajaj', 'activa')


In [163]:
[i.upper() for i in mytuple1 ]

['HERO HONDA', 'MARUTI', 'SPENDER', 'BAJAJ', 'ACTIVA', 'VIVPA']

In [164]:
[i.lower() for i in mytuple1 ]

['hero honda', 'maruti', 'spender', 'bajaj', 'activa', 'vivpa']

In [165]:
[print(i) for i in mytuple1 if "a" in i ]

Hero Honda
Maruti
bajaj
activa


[None, None, None, None]

# set

In [166]:
a={"Abhishek","rohit","aniket","baba"}#Unorder #unchanble #duplicated not allowed
print(type(a))
print(len(a))

<class 'set'>
4


In [167]:
"Abhishek" in a

True

In [168]:
if "Abhishek" in a:
    print("it is true")
else:
    print("it is wrog")

it is true


In [169]:
a.add("pande")
a.add("sklill")
a

{'Abhishek', 'aniket', 'baba', 'pande', 'rohit', 'sklill'}

In [170]:
a.remove("sklill")
a.remove("pande")
a

{'Abhishek', 'aniket', 'baba', 'rohit'}

In [171]:
a.discard("baba")
a

{'Abhishek', 'aniket', 'rohit'}

In [172]:
myset1={"asus","hp","dell","apple","lenovo","gammimg"}
myset2={2033,"hp","dell",25604,5685,458}

In [173]:
myset1.update(myset2)
myset1

{2033, 25604, 458, 5685, 'apple', 'asus', 'dell', 'gammimg', 'hp', 'lenovo'}

In [174]:
myset1.union(myset2)
myset1

{2033, 25604, 458, 5685, 'apple', 'asus', 'dell', 'gammimg', 'hp', 'lenovo'}

In [175]:
for i in myset1:
    print(i)

25604
lenovo
hp
458
dell
2033
apple
5685
asus
gammimg


In [176]:
myset1.intersection_update(myset2)
myset1

{2033, 25604, 458, 5685, 'dell', 'hp'}

In [177]:
myset1.symmetric_difference_update(myset2)
myset1

set()

In [178]:
x={"Microsoft","Google","Apple"} #return same string
y={"Microsoft","Sunder Pichai","Apple"}
x.intersection_update(y)
x

{'Apple', 'Microsoft'}

In [179]:
x.symmetric_difference_update(y)
x

{'Sunder Pichai'}

In [180]:
x.symmetric_difference(y)
x

{'Sunder Pichai'}

In [181]:
x.clear()
x

set()

In [182]:
del x

# Dictionari

In [183]:
name={"abhishek":20,"rohit":14,"shanker":16,"aniket":22,"color":["black","grenn","red"]}
np={"maharathra":"Aurangabd","karnatka":"Banglore","Madya pradesh":"Indor"}
print(name)
print(len(name))
print(type(name))
print(np)

{'abhishek': 20, 'rohit': 14, 'shanker': 16, 'aniket': 22, 'color': ['black', 'grenn', 'red']}
5
<class 'dict'>
{'maharathra': 'Aurangabd', 'karnatka': 'Banglore', 'Madya pradesh': 'Indor'}


In [184]:
name.update(np)

In [185]:
name.popitem()

('Madya pradesh', 'Indor')

In [186]:
name

{'abhishek': 20,
 'rohit': 14,
 'shanker': 16,
 'aniket': 22,
 'color': ['black', 'grenn', 'red'],
 'maharathra': 'Aurangabd',
 'karnatka': 'Banglore'}

In [187]:
name["abhishek"]
name["rohit"]
name["color"]

['black', 'grenn', 'red']

In [188]:
name["Laptop"]="Asus"
name["hp"]="mouse"
name

{'abhishek': 20,
 'rohit': 14,
 'shanker': 16,
 'aniket': 22,
 'color': ['black', 'grenn', 'red'],
 'maharathra': 'Aurangabd',
 'karnatka': 'Banglore',
 'Laptop': 'Asus',
 'hp': 'mouse'}

In [189]:
name.keys()

dict_keys(['abhishek', 'rohit', 'shanker', 'aniket', 'color', 'maharathra', 'karnatka', 'Laptop', 'hp'])

In [190]:
name.items()

dict_items([('abhishek', 20), ('rohit', 14), ('shanker', 16), ('aniket', 22), ('color', ['black', 'grenn', 'red']), ('maharathra', 'Aurangabd'), ('karnatka', 'Banglore'), ('Laptop', 'Asus'), ('hp', 'mouse')])

In [191]:
name.values()

dict_values([20, 14, 16, 22, ['black', 'grenn', 'red'], 'Aurangabd', 'Banglore', 'Asus', 'mouse'])

In [192]:
name["hp"]=12000
name

{'abhishek': 20,
 'rohit': 14,
 'shanker': 16,
 'aniket': 22,
 'color': ['black', 'grenn', 'red'],
 'maharathra': 'Aurangabd',
 'karnatka': 'Banglore',
 'Laptop': 'Asus',
 'hp': 12000}

In [193]:
name["Laptop"]=30000
name

{'abhishek': 20,
 'rohit': 14,
 'shanker': 16,
 'aniket': 22,
 'color': ['black', 'grenn', 'red'],
 'maharathra': 'Aurangabd',
 'karnatka': 'Banglore',
 'Laptop': 30000,
 'hp': 12000}

In [194]:
if "abhishek" in name:
    print("it is true")
else:
    print("gii")

it is true


In [195]:
name["Laptop"]="ASUS" #update
name

{'abhishek': 20,
 'rohit': 14,
 'shanker': 16,
 'aniket': 22,
 'color': ['black', 'grenn', 'red'],
 'maharathra': 'Aurangabd',
 'karnatka': 'Banglore',
 'Laptop': 'ASUS',
 'hp': 12000}

In [196]:
name.pop("Laptop")#delete
name

{'abhishek': 20,
 'rohit': 14,
 'shanker': 16,
 'aniket': 22,
 'color': ['black', 'grenn', 'red'],
 'maharathra': 'Aurangabd',
 'karnatka': 'Banglore',
 'hp': 12000}

In [197]:
for i in name:
    print(i)

abhishek
rohit
shanker
aniket
color
maharathra
karnatka
hp


In [198]:
for i in name.keys():
    print(i)

abhishek
rohit
shanker
aniket
color
maharathra
karnatka
hp


In [199]:
for i in name.items():
    print(i)

('abhishek', 20)
('rohit', 14)
('shanker', 16)
('aniket', 22)
('color', ['black', 'grenn', 'red'])
('maharathra', 'Aurangabd')
('karnatka', 'Banglore')
('hp', 12000)


In [200]:
for i in name.values():
    print(i)

20
14
16
22
['black', 'grenn', 'red']
Aurangabd
Banglore
12000


In [201]:
name.clear()

In [202]:
name

{}

In [203]:
del name

In [204]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [205]:
a="abhishek"

In [206]:
a.count("h")

2

In [207]:
a.count("e")

1

In [208]:
a="i am new in your country can you help me out? "

In [209]:
a.count("o")

4

In [210]:
a.partition("country")

('i am new in your ', 'country', ' can you help me out? ')

In [211]:
a.rstrip()

'i am new in your country can you help me out?'

In [212]:
a.lstrip()

'i am new in your country can you help me out? '

In [213]:
a.strip()

'i am new in your country can you help me out?'

In [214]:
a.startswith("n")

False

In [215]:
a.startswith("i")

True

In [216]:
a.endswith("t")

False

In [217]:
a.upper()

'I AM NEW IN YOUR COUNTRY CAN YOU HELP ME OUT? '

In [218]:
a.lower()

'i am new in your country can you help me out? '

In [219]:
a.split()

['i', 'am', 'new', 'in', 'your', 'country', 'can', 'you', 'help', 'me', 'out?']

In [220]:
print(type(a))
print(len(a))
print(a)

<class 'str'>
46
i am new in your country can you help me out? 


In [221]:
a=str(input("enter the age: "))

enter the age: abhishek


In [222]:
a="i want a laptop but i don't buy untill price {}"
b=45000

In [223]:
print(a.format(b))

i want a laptop but i don't buy untill price 45000


In [224]:
c="my salary is {}"
v=12000
print(c.format(v))

my salary is 12000


In [225]:
import datetime
a=datetime.datetime.now()
a

datetime.datetime(2024, 1, 31, 19, 2, 15, 886539)

In [226]:
a.strftime("%a")
a.strftime("%A")
a.strftime("%x")

'01/31/24'

In [227]:
a=34
b=34
if a<b:
    print("its okkk")
else:
    print("not okk")

not okk


In [228]:
if a<b and a>b:
    print("it is okkk")
else:
    print("olkkk")

olkkk


In [229]:
if a>b or a<b:
    print("thick hai")
else:
    print("thick nahi hai")

thick nahi hai


In [230]:
if a==b:
    print("a is similar to b")
if a>b:
    print("a is grether than b")

a is similar to b


In [238]:
a=20
b=30
while a<b:
    a+=1
    print(a)

21
22
23
24
25
26
27
28
29
30


In [240]:
while a<b and a>b:
    a+=1
    print(a)

In [1]:
i=10
while i<20:
    print(i)
    if (i == 15):
        break
    i += 1

10
11
12
13
14
15


In [5]:
i=10
while i<20:
    i+=1
    if (i==15):
        continue
    print(i)
    

11
12
13
14
16
17
18
19
20


In [19]:
a=["abhishekj","vishau","math"]
for i in a:
    print(i)

abhishekj
vishau
math


In [20]:
for i in range(len(a)):
    print(a[i])

abhishekj
vishau
math


In [25]:
n=[]
for i in a:
    if "s" in i:
        n.append(i)
print(n)

['abhishekj', 'vishau']


In [31]:
for i in range(10,20):
    print(i)

10
11
12
13
14
15
16
17
18
19


In [33]:
fruits = ["apple", "banana", "cherry"]
for i in fruits:
    if i=="banana":
        break
    print(i)

apple


In [85]:
mylist=["Abhishek","SHanker","vishal","vani","pande"]
mylist1=["chcha","mama","kaka","nana"]
print(mylist)
print(type(mylist))
print(len(mylist))
print(mylist1)

['Abhishek', 'SHanker', 'vishal', 'vani', 'pande']
<class 'list'>
5
['chcha', 'mama', 'kaka', 'nana']


In [70]:
mylist[1]="SHANKER"

In [71]:
mylist.append("laptop")

In [72]:
mylist

['Abhishek', 'SHANKER', 'vishal', 'vani', 'pande', 'laptop']

In [73]:
mylist.remove("laptop")

In [74]:
mylist

['Abhishek', 'SHANKER', 'vishal', 'vani', 'pande']

In [75]:
mylist.insert(1,"rohit")

In [76]:
mylist

['Abhishek', 'rohit', 'SHANKER', 'vishal', 'vani', 'pande']

In [77]:
mylist[::-1]

['pande', 'vani', 'vishal', 'SHANKER', 'rohit', 'Abhishek']

In [78]:
mylist.count("a")

0

In [80]:
mylist.sort()
mylist

['Abhishek', 'SHANKER', 'pande', 'rohit', 'vani', 'vishal']

In [81]:
mylist.reverse()
mylist

['vishal', 'vani', 'rohit', 'pande', 'SHANKER', 'Abhishek']

In [86]:
mylist.extend(mylist1)

In [87]:
mylist

['Abhishek',
 'SHanker',
 'vishal',
 'vani',
 'pande',
 'chcha',
 'mama',
 'kaka',
 'nana']

In [88]:
if "Abhishek" in mylist:
    print("it is true")

it is true


In [91]:
i=0
while i<len(mylist):
    print(mylist[i])
    i+=1

Abhishek
SHanker
vishal
vani
pande
chcha
mama
kaka
nana


In [92]:
for i in mylist:
    print(i)

Abhishek
SHanker
vishal
vani
pande
chcha
mama
kaka
nana


In [100]:
nwe=[i for i in mylist if "a" in i]

In [101]:
nwe

['SHanker', 'vishal', 'vani', 'pande', 'chcha', 'mama', 'kaka', 'nana']

In [143]:
s={"abhishek","rohit","rohit","abhishek"}
n={"i phone ","redmi",45,"MAMA"}

In [144]:
s.add("BABA")

In [145]:
s.union(n)

{45, 'BABA', 'MAMA', 'abhishek', 'i phone ', 'redmi', 'rohit'}

In [146]:
p=s.update(n)
p

In [147]:
s.remove("BABA")

In [148]:
s

{45, 'MAMA', 'abhishek', 'i phone ', 'redmi', 'rohit'}

In [149]:
s.discard("rohit")
s

{45, 'MAMA', 'abhishek', 'i phone ', 'redmi'}

In [150]:
s.intersection(n)

{45, 'MAMA', 'i phone ', 'redmi'}

In [151]:
s.intersection_update(n)

In [152]:
s

{45, 'MAMA', 'i phone ', 'redmi'}

In [153]:
s.symmetric_difference(n)

set()

## User Define Function

In [22]:
def abhishek():
    print("hi i am abhishek")
abhishek()Even

hi i am abhishek


In [27]:
def greet():
    return "Hello Abhishek"
greet()

'Hello Abhishek'

In [37]:
def greeet(items):
    return items*5
greeet(5)
greeet(7)

35

In [44]:
def calculator(a,b):
    print("addition :",a+b)
calculator(2,3)
calculator(10,10)

addition : 5
addition : 20


In [140]:
def add(x,y):
    return x+y
print(add(3,3))

6


In [52]:
def laptop_price(HP,ASUS,LENOVO,DELL,VIVOBOOK15):
    print("HP PRICE IS :",HP)
    print("ASUS PRICE IS :",ASUS)
    print("LENOVO PRICE IS :",LENOVO)
    print("DELL PRICE IS :",DELL)
    print("VIVOBOOK15 PRICE IS :",VIVOBOOK15)
laptop_price(56000,45000,25000,85000,40000)

HP PRICE IS : 56000
ASUS PRICE IS : 45000
LENOVO PRICE IS : 25000
DELL PRICE IS : 85000
VIVOBOOK15 PRICE IS : 40000


In [128]:
def grether_value(number):
    if number>45:
        return True

In [129]:
lst = [12, 6, 83, 55, 49, 66, 4, 22]
result=list(filter(grether_value,lst))
print(result)

[83, 55, 49, 66]


In [64]:
def mobile_price(APPLE,SUMSUNG,VIVO,OPPO,REDMI,ONEPLUS,LAVA):
    print("APPLE price is :",APPLE)
    print("SUMSUNG price is :",SUMSUNG)
    print("VIVO price is :",VIVO)
    print("OPPO price is :",OPPO)
    print("REDMI price is :",REDMI)
    print("ONEPLUS price is :",ONEPLUS)
    print("LAVA price is :",LAVA)
print("-------------------------------Frist_line-------------------------------------------")
mobile_price(150000,34000,15000,12000,17000,50000,7000)
print("-------------------------------Second_line------------------------------------------")
mobile_price(45000,3000,17000,2000,18000,40000,4000)
print("--------------------------------Third_line------------------------------------------")
mobile_price(170000,6000,9000,2000,6000,80000,1000)
print("---------------------------------End------------------------------------------------")

-------------------------------Frist_line-------------------------------------------
APPLE price is : 150000
SUMSUNG price is : 34000
VIVO price is : 15000
OPPO price is : 12000
REDMI price is : 17000
ONEPLUS price is : 50000
LAVA price is : 7000
-------------------------------Second_line------------------------------------------
APPLE price is : 45000
SUMSUNG price is : 3000
VIVO price is : 17000
OPPO price is : 2000
REDMI price is : 18000
ONEPLUS price is : 40000
LAVA price is : 4000
--------------------------------Third_line------------------------------------------
APPLE price is : 170000
SUMSUNG price is : 6000
VIVO price is : 9000
OPPO price is : 2000
REDMI price is : 6000
ONEPLUS price is : 80000
LAVA price is : 1000
---------------------------------End------------------------------------------------


In [72]:
def family_info(NAME,SCHOOL,FATHER,MOTHER,BROTHER,SISTER):
    print("Name of student",NAME)
    print("School name",SCHOOL)
    print("Father name",FATHER)
    print("Monther name",MOTHER)
    print("Brother name",BROTHER)
    print("Sister name",SISTER)
family_info(NAME=": Sadhana dighule",SCHOOL=": bagvati vidya mandir",FATHER=": suresh",MOTHER=": savita",BROTHER=": vitthal",SISTER=": samta")

Name of student : Sadhana dighule
School name : bagvati vidya mandir
Father name : suresh
Monther name : savita
Brother name : vitthal
Sister name : samta


In [77]:
def personal_info(school,age,marks,city):
    print("School name :",school)
    print("Age :",age)
    print("Marks :",marks)
    print("City name:",city)
personal_info(school="Bagvati VIdya Mandir",age="8.2",marks="12",city="Smabajinagar")

School name : Bagvati VIdya Mandir
Age : 8.2
Marks : 12
City name: Smabajinagar


In [113]:
def even(number):
    if number%2==0:
        print("the number {} is Even".format(number))
    else:
        print("the number {} is odd".format(number))
even(2)

the number 2 is Even


In [123]:
list1=[1,2,3,4,5,6,7,8,9,10]
def multiply(number):
    return number*5
final_ans=map(multiply,list1)
print(list(final_ans))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [131]:
def celsius_to_fahrenheit(k):
    return (k *9/5)+32
celsius_to_fahrenheit(17)

62.6

In [132]:
def C(k):
    return (k *9/5)+32
tem_1=[10,23,34,24,55]
result=map(celsius_to_fahrenheit,tem_1)
print(list(result))

[50.0, 73.4, 93.2, 75.2, 131.0]


In [139]:
def EVEN(number):
    return number%2==0
list2=[1,2,3,4,5,6,7,8,9,10]
result=map(EVEN,list2)
print(list(result))

[False, True, False, True, False, True, False, True, False, True]


In [3]:
def get_vowels(string):
  vowels = "aeiouAEIOU" # A string containing all the vowels
  vowel_list = [] # An empty list to store the vowels
  for char in string: # Loop over each character in the string
    if char in vowels: # Check if the character is a vowel
      vowel_list.append(char) # Append the vowel to the list
  return vowel_list # Return the list of vowels

In [4]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
for word in words1:
  print(get_vowels(word))

['a', 'e']
['a', 'a', 'a']
['e']
['o', 'a', 'e']
['e', 'o']


## Lambda function

when you have list then you can uses following function.......
* map---you want each and every element then you can use map function
* filter---you want specifice value then you can use filter function
* reduce----you want to use only 1 value

## Basic

In [142]:
add1=lambda x,y:x+y
print(add1(3,3))

6


In [144]:
print((lambda x,y: x+y)(5,5))

10


In [200]:
l1=lambda x,y: x*y
l1(10,10)

100

In [204]:
l5=lambda x: x*x
l5(5)

25

In [150]:
c=lambda c: c*10
c(10)

100

In [149]:
l2=lambda x: x%2==0
l2(16)

True

In [151]:
l3=lambda c:c*9/5 +32
print(l3(10))

50.0


In [175]:
#used basic lambda function
l4=lambda x: x/500
print("percentage of first year")
print(l4(485))


print("----------------------------------------------")

#used anyonomus function
print((lambda x: x/500)(485))
print("----------------------------------------------")

#used user define function
def percentage(x,y):
    print("percentage of first year",x/y)
percentage(485,500)

percentage of first year
0.97
----------------------------------------------
0.97
----------------------------------------------
percentage of first year 0.97


In [197]:
from functools import reduce # You need to import this module to use reduce() in Python 3
sum_of_list3 = reduce(lambda x, y: x+y, list3)
print(sum_of_list3)

49


In [196]:
even_list3 = list(filter(lambda x: x%2 == 0, list3))
print(even_list3)

[2, 4, 8, 6, 4, 10]


In [195]:
squared_list3 = list(map(lambda x: x*x, list3))
print(squared_list3)

[4, 9, 25, 16, 49, 64, 36, 16, 100]


In [198]:
length=lambda x: len(x)
print(length("abhishek"))

8


## map

In [209]:
tem_3=[10,23,34,24,55]
p=list(map(lambda c:c*9/5 +32,tem_1))
print(list(p))

[50.0, 73.4, 93.2, 75.2, 131.0]


In [8]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
vowels = "aeiou" # A string containing all the vowels
vowels_from_words1 = [letter for word in words1 for letter in word if letter in vowels]
print(vowels_from_words1)

['a', 'e', 'a', 'a', 'a', 'e', 'o', 'a', 'e', 'e', 'o']


In [36]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
vowels = "aeiou" # A string containing all the vowels
vowels_from_words1 = [c for i in words1 for c in i if c in "aeiou"]
print(vowels_from_words1)

['a', 'e', 'a', 'a', 'a', 'e', 'o', 'a', 'e', 'e', 'o']


In [24]:
# Define a function that counts the number of vowels in a word
def count_vowels(word):
    vowels = "aeiou"
    count = 0
    for letter in word.lower():
        if letter in vowels:
            count += 1
    return count

# Create a list of words
words = ["apple", "banana", "cherry", "orange", "lemon"]

# Use the map function to apply the counting function to the list
vowel_counts = map(count_vowels, words)

# Convert the map object to a list and print it
print(list(vowel_counts)) # [2, 3, 2, 3, 2]

[2, 3, 1, 3, 2]


In [38]:
string="hi i am abhishek i am from india"
vowels=[string.count(x)for x in "aeiou"]
print(sum(vowels))

12


In [70]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
vowel = list(map(lambda a: list(x for x in a if x in "aeiou"), words1))
print(vowel)

[['a', 'e'], ['a', 'a', 'a'], ['e'], ['o', 'a', 'e'], ['e', 'o']]


In [73]:
words1 = ["abhishek", "suresh", "damodhar", "rohit", "shanker"]
vowel = lambda a: list(i for i in a if i in "aeiou")
result=list(map(vowel,words1))
print(result)

[['a', 'i', 'e'], ['u', 'e'], ['a', 'o', 'a'], ['o', 'i'], ['a', 'e']]


In [75]:
words1 = "opppo", "vivo", "redmi", "sumsung", "apple"
vowel = lambda a: list(i for i in a if i in "aeiou")
result=list(map(vowel,words1))
print(result)

[['o', 'o'], ['i', 'o'], ['e', 'i'], ['u', 'u'], ['a', 'e']]


In [89]:
#sorted Alpfabetically
words3 = ["abhishek", "shanker", "rohit", "anirudh", "vitthal"]
sorted(words3,key=lambda x:x)

['abhishek', 'anirudh', 'rohit', 'shanker', 'vitthal']

In [90]:
#sorted by length
words4 = ["abhishek", "shanker", "rohit", "anirudh", "vitthal"]
sorted(words4,key=lambda x: len(x))

['rohit', 'shanker', 'anirudh', 'vitthal', 'abhishek']

In [91]:
#finding maximam value in a dictonari
data={"a":20,"b":2,"c":16,"d":45}
max(data,key=lambda x: x)

'd'

In [126]:
#finding minimum value in a dictonari
data={"a":20,"b":2,"c":16,"d":45}
min(data,key=lambda x: x)

'a'

## filter

In [122]:
a=[4,12,35,36,90,44,63,28]
maxwell = [x for x in a if x > 45] # Using list comprehension
print(maxwell)
maxwell = list(filter(lambda x: x > 45, a)) # Using filter function
print(maxwell)
maxwell= list(filter(lambda x: x<50,a))
print(list(maxwell))

[90, 63]
[90, 63]
[4, 12, 35, 36, 44, 28]


In [138]:
list4=[111,37,6,14,21,66,81,31,57]
def prime_number(number):
    return number%2==0
result=list(filter(prime_number,list4))
print(result)

[6, 14, 66]


In [140]:
def maximam_number(number):
    return number>50
result=list(filter(maximam_number,list4))
print(result)

[111, 66, 81, 57]


In [142]:
def Minimum_Number(number):
    return number<50
result=list(filter(Minimum_Number,list4))
print(result)

[37, 6, 14, 21, 31]


In [145]:
even_number=list(filter(lambda x: x%2==0,list4))
print(even_number)

[6, 14, 66]


In [4]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
def words(letters):
    return 'a' in letters # Returns True if 'a' is in letters, False otherwise
result=list(filter(words,words1))
print(result)

['apple', 'banana', 'orange']


In [7]:
words1 = ["apple", "banana", "cherry", "orange", "lemon"]
words_with_a = lambda list_of_words: list(filter(words, list_of_words))
print(words_with_a(words1))

['apple', 'banana', 'orange']


In [10]:
def letters(world):
    return world[0]=="a"
result=list(filter(letters,words1))
print(result)

['apple']


In [8]:
words = ["apple", "banana", "cherry", "orange", "lemon"]
words_starting_with_a = filter(lambda word: word[0] == 'a', words)
print(list(words_starting_with_a))

['apple']


## Reduce

In [11]:
from functools import reduce

In [16]:
number=[10,23,43,25,30]
def addition(x,y):
    return x+y
result=reduce(addition,number)
print(result)

131


In [18]:
result=reduce(lambda x,y: x+y,number)
print(result)

131


In [23]:
number=[25,10,2,1,0]
def addition(x,y):
    return x-y
result=reduce(addition,number)
print(result)

12


In [24]:
result=reduce(lambda x,y: x-y,number)
print(result)

12


In [26]:
number=[12,14,48,56]
def addition(x,y):
    return x*y
result=reduce(addition,number)
print(result)

451584


In [27]:
result=reduce(lambda x,y: x*y,number)
print(result)

451584


In [28]:
number=[12,14,48,56]
def addition(x,y):
    return x/y
result=reduce(addition,number)
print(result)

0.00031887755102040814


In [29]:
result=reduce(lambda x,y: x/y,number)
print(result)

0.00031887755102040814


In [32]:
numbers=[10,15,31,55,10]
result=reduce(lambda x,y:x+y ,map(lambda x: x*x,numbers))
print(result)

4411


## Numpy

In [2]:
import numpy as np
a=np.array([])#empty array
print("version :",np.__version__)
print("--------------------------------------------------------------------")
print(a)
print(type(a))
print(len(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)
print("--------------------------------------------------------------------")
a=np.array([10,20,30,40,50])
print(a)
print(type)
print(len(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)
print("--------------------------------------------------------------------")
a=np.array((10,20,30,40,50))
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)
print("--------------------------------------------------------------------")
a=np.array({10,20,30,40,50})
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)
print("--------------------------------------------------------------------")
a=np.array({"a":10,"b":20,"c":30})
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)
print("--------------------------------------------------------------------")
a=np.array([10,True,"abhishek",4.4])
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)
print("--------------------------------------------------------------------")
a=np.array(["abhishek","suresh","vitthal","sadhana"])
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

version : 1.25.2
--------------------------------------------------------------------
[]
<class 'numpy.ndarray'>
0
(0,)
0
float64
1
--------------------------------------------------------------------
[10 20 30 40 50]
<class 'type'>
5
(5,)
5
int32
1
--------------------------------------------------------------------
[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)
5
int32
1
--------------------------------------------------------------------
{50, 20, 40, 10, 30}
<class 'numpy.ndarray'>
()
1
object
0
--------------------------------------------------------------------
{'a': 10, 'b': 20, 'c': 30}
<class 'numpy.ndarray'>
()
1
object
0
--------------------------------------------------------------------
['10' 'True' 'abhishek' '4.4']
<class 'numpy.ndarray'>
(4,)
4
<U32
1
--------------------------------------------------------------------
['abhishek' 'suresh' 'vitthal' 'sadhana']
<class 'numpy.ndarray'>
(4,)
4
<U8
1


In [3]:
print(a[1])
print(a[::-1])
print(a[-1])
print(a[2])

suresh
['sadhana' 'vitthal' 'suresh' 'abhishek']
sadhana
vitthal


In [37]:
a=np.array([10,20,30,40,50])#1D array
print(a.ndim)
a=np.array([[10,20],[30,40],[50,60]])#2D array
print(a.ndim)
a=np.array([[[10,20,30],[40,50,60],[70,80,90]]])#3D array
print(a.ndim)
a=np.array([3,3,4,5,6],ndmin=5)
print(a.ndim)

1
2
3
5


In [35]:
list1=[10,20,30]
list2=[12,14,15]
list3=[19,17,55]
a=np.array([list1+list2+list3]).reshape(3,3)
print(a)
print(type(a))
print(a.dtype)
print(len(a))
print(a.shape)
a=a.astype(float)
print(a.dtype)
print(a)
print(a.size)
print(a.ndim)
print(a)
x=a.copy()
print(x)
y=a.view()
print(y)

[[10 20 30]
 [12 14 15]
 [19 17 55]]
<class 'numpy.ndarray'>
int32
3
(3, 3)
float64
[[10. 20. 30.]
 [12. 14. 15.]
 [19. 17. 55.]]
9
2
[[10. 20. 30.]
 [12. 14. 15.]
 [19. 17. 55.]]
[[10. 20. 30.]
 [12. 14. 15.]
 [19. 17. 55.]]
[[10. 20. 30.]
 [12. 14. 15.]
 [19. 17. 55.]]


In [6]:
for i in a:
    print(i)

[10. 20. 30. 12. 14. 15. 19. 17. 55.]


In [7]:
for i in np.nditer(a):
    print(i)

10.0
20.0
30.0
12.0
14.0
15.0
19.0
17.0
55.0


In [8]:
list4=np.concatenate((list1,list2,list3))
print(list4)

[10 20 30 12 14 15 19 17 55]


In [116]:
a=np.array_split(list4,4)
print(a)
a=np.array_split(list4,2)
print(a)

[array([10, 20, 30]), array([12, 14]), array([15, 19]), array([17, 55])]
[array([10, 20, 30, 12, 14]), array([15, 19, 17, 55])]


In [8]:
a=np.array([1,2,3,4,2,1,8,4,6,7,2,5,8,4,6,9,2,9])
b=np.where(a==2)
print(b)
b=np.where(a==4)
print(b)
b=np.where(a==8)
print(b)
b=np.where(a==5)
print(b)
b=np.where(a==11)
print(b)
print("-----------------------------------------------")
a=np.searchsorted(a,2)
print(a)

(array([ 1,  4, 10, 16], dtype=int64),)
(array([ 3,  7, 13], dtype=int64),)
(array([ 6, 12], dtype=int64),)
(array([11], dtype=int64),)
(array([], dtype=int64),)
-----------------------------------------------
1


In [142]:
list5=["abhishek","suresh","vitthal","shanker","rohit"]
list5=np.array([list5])
print(np.sort(list5))

[['abhishek' 'rohit' 'shanker' 'suresh' 'vitthal']]


In [149]:
list6=np.array(["pratik","vishal","surya","mode"])
list6[1]="abhi"
list6[2]="mobile"
list6

array(['pratik', 'abhi', 'mobile', 'mode'], dtype='<U6')

In [153]:
arr1=np.dstack((list1,list2))
print(arr1)

[[[10 12]
  [20 14]
  [30 15]]]


In [154]:
arr2=np.hstack((list1,list2))
print(arr2)

[10 20 30 12 14 15]


In [155]:
arr3=np.vstack((list1,list2))
print(arr3)

[[10 20 30]
 [12 14 15]]


In [160]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [161]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [164]:
print(np.eye((5)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [169]:
print(np.full((5,6),2))

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [8]:
import numpy as np
print(np.empty((5,5)))

[[4.67296746e-307 1.69121096e-306 4.67293691e-307 1.33511018e-306
  1.33511969e-306]
 [6.23037996e-307 6.23053954e-307 9.34609790e-307 8.45593934e-307
  9.34600963e-307]
 [1.86921143e-306 6.23061763e-307 8.90104239e-307 6.89804132e-307
  9.34605716e-307]
 [1.37962456e-306 1.42418172e-306 8.06609645e-308 6.89810244e-307
  1.22387550e-307]
 [2.22522596e-306 8.34423917e-308 1.11261162e-306 1.78021527e-306
  2.46151512e-312]]


In [6]:
print(np.arange(4))
print(np.arange(10,20))
print(np.arange(10,20,2))

[0 1 2 3]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [249]:
print(np.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [185]:
print(np.random.random((1)))
print(np.random.random((10)))

[0.61504351]
[0.76582754 0.61396027 0.59272127 0.68911839 0.56829927 0.23068779
 0.66236279 0.64512416 0.6707885  0.91727039]


In [191]:
import random
print(random.randint(0,50))

40


In [208]:
print(list1)
print(list2)
print(np.add(list1,list2))
print(np.subtract(list1,list2))
print(np.multiply(list1,list2))
print(np.divide(list1,list2))

[10, 20, 30]
[12, 14, 15]
[22 34 45]
[-2  6 15]
[120 280 450]
[0.83333333 1.42857143 2.        ]


In [212]:
s=np.array([1,5,4,8,3,6,4,7,8,5,18])
print(s.min())
print(s.max())
print(s.mean())
print(s.cumsum())
print(s.sum())
print(s.std())
print(s.ravel())

1
18
6.2727272727272725
[ 1  6 10 18 21 27 31 38 46 51 69]
69
4.223116236122522
[ 1  5  4  8  3  6  4  7  8  5 18]


In [213]:
#i=np.transpose(a)
#a=np.delete(a,[6])
#a=np.append(b,2)
#kkk=np.insert(b,1,2)

In [26]:
a=np.array([1,2,3,4,5,6])
a=np.array((1,2,3,4,5))
b=np.array({1,2,4,5,6,7})
a=np.array({"a":4,"b":2,"c":5})
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.shape)

{'a': 4, 'b': 2, 'c': 5}
<class 'numpy.ndarray'>
object
0
1
()


In [42]:
a=np.array([10])
print(a)
print("Number of dimention :",a.ndim)
a=np.array([[10,20,40,50]])
print(a)
print("Number of dimention :",a.ndim)
a=np.array([[[10,20,50,40,70]]])
print(a)
print("Number of dimention :",a.ndim)
a=np.array([[[[10,20,30,40,50,60]]]])
print(a)
print("Number of dimention :",a.ndim)  
print("------------------------------------------------")
a=np.array([10,20,30,40,50,60],ndmin=10)
print(a)
print("Number of dimention :",a.ndim)

[10]
Number of dimention : 1
[[10 20 40 50]]
Number of dimention : 2
[[[10 20 50 40 70]]]
Number of dimention : 3
[[[[10 20 30 40 50 60]]]]
Number of dimention : 4
------------------------------------------------
[[[[[[[[[[10 20 30 40 50 60]]]]]]]]]]
Number of dimention : 10


In [54]:
list1=[50,10,20,40,80]
list2=[70,78,79,45,12]
list3=[12,45,25,78,65]
a=np.array((list1+list2+list3))
print(a)
print(a.reshape(5,3))
print(a.dtype)
a=a.astype(float)
print(a)
print(a.reshape(5,3))

[50 10 20 40 80 70 78 79 45 12 12 45 25 78 65]
[[50 10 20]
 [40 80 70]
 [78 79 45]
 [12 12 45]
 [25 78 65]]
int32
[50. 10. 20. 40. 80. 70. 78. 79. 45. 12. 12. 45. 25. 78. 65.]
[[50. 10. 20.]
 [40. 80. 70.]
 [78. 79. 45.]
 [12. 12. 45.]
 [25. 78. 65.]]


In [58]:
a=np.concatenate((list1,list2,list3)).reshape(5,3)
print(a)
print(a.shape)

[[50 10 20]
 [40 80 70]
 [78 79 45]
 [12 12 45]
 [25 78 65]]
(5, 3)


In [66]:
a=np.array_split(list1,2)
print(a)
a=np.array_split(list2,3)
print(a)

[array([50, 10, 20]), array([40, 80])]
[array([70, 78]), array([79, 45]), array([12])]


In [193]:
a=np.array([1,5,4,2,3,6,1,8,9,5,6,4,7,8,5])
b=np.array(["apple","mango","abhi","jackfruit","pumkin"])
print(np.sort(a))
print(np.sort((b)))

[1 1 2 3 4 4 5 5 5 6 6 7 8 8 9]
['abhi' 'apple' 'jackfruit' 'mango' 'pumkin']


In [104]:
b=np.where(a==2)
print(b)

(array([3], dtype=int64),)


In [105]:
c=np.where(a==5)
print(c)

(array([ 1,  9, 14], dtype=int64),)


In [106]:
a[5]=60
a[13]=80
print(a)

[ 1  5  4  2  3 60  1  8  9  5  6  4  7 80  5]


In [113]:
b=np.array(["apple","mango","abhi","jackfruit","pumkin"])
print(type(b))
b[1]="MNAGO"
b[2]="ABHISHEK"

<class 'numpy.ndarray'>


In [114]:
print(b)

['apple' 'MNAGO' 'ABHISHEK' 'jackfruit' 'pumkin']


In [115]:
print(np.dstack((a)))

[[[ 1  5  4  2  3 60  1  8  9  5  6  4  7 80  5]]]


In [116]:
print(np.vstack(a))

[[ 1]
 [ 5]
 [ 4]
 [ 2]
 [ 3]
 [60]
 [ 1]
 [ 8]
 [ 9]
 [ 5]
 [ 6]
 [ 4]
 [ 7]
 [80]
 [ 5]]


In [117]:
print(np.hstack(a))

[ 1  5  4  2  3 60  1  8  9  5  6  4  7 80  5]


In [123]:
print(np.zeros(5))
print("--------------------")
print(np.zeros((5,5)))

[0. 0. 0. 0. 0.]
--------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [125]:
print(np.ones(10))
print("-----------------")
print(np.ones((5,5)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [133]:
print(np.eye(5))
np.eye(5,5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [138]:
print(np.full((5,5),2))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [139]:
print(np.empty((5,5)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [148]:
print(np.arange(0,51,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


In [149]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [165]:
print(np.linspace(0,10))


[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [167]:
print(np.random.random(10)) #you can get different value every time 
print("----------------------------------------------")
print(np.random.random(20))

[0.68957668 0.10635625 0.47713042 0.33068455 0.87695341 0.7922936
 0.76090104 0.16647984 0.21968625 0.81038808]
----------------------------------------------
[0.42588533 0.14996245 0.47717387 0.50264085 0.19416813 0.271252
 0.56735472 0.62171524 0.41701567 0.21160353 0.81379861 0.40179497
 0.15219489 0.80219236 0.2067731  0.49625646 0.38488603 0.74239123
 0.6801664  0.15478464]


In [252]:
import random #you can get different value every time 
print("Different Value",np.random.randint(10))
print("Different Value",np.random.randint(0,20,5))

Different Value 7
Different Value [ 4 15  7 16  3]


In [232]:
x=np.array([10,20,30,40,50])
y=np.array([5,10,15,20,25])

In [233]:
print(x)
print(y)

[10 20 30 40 50]
[ 5 10 15 20 25]


In [234]:
print("-------------ADDITION--------------------")
print(np.add(x,y))
print("-------------SUBTRACTION--------------------")
print(np.subtract(x,y))
print("-------------MULTIPLICATION--------------------")
print(np.multiply(x,y))
print("-------------DIVITION--------------------")
print(np.divide(x,y))

-------------ADDITION--------------------
[15 30 45 60 75]
-------------SUBTRACTION--------------------
[ 5 10 15 20 25]
-------------MULTIPLICATION--------------------
[  50  200  450  800 1250]
-------------DIVITION--------------------
[2. 2. 2. 2. 2.]


In [238]:
print(" Sum of x     :", np.sum(x))
print(" Sum of y     :", np.sum(y))
print(" Minimum of x :", np.min(x))
print(" Minimum of y :", np.min(y))
print(" Maximam of x :", np.max(x))
print(" Maximam of y :", np.max(y))
print(" Mean of x    :", np.mean(x))
print(" Mean of y    :", np.mean(y))
print(" std of x     :", np.std(x))
print(" std of y     :", np.std(y))
print(" Cumsum of x  :", np.cumsum(x))
print(" Cumsum of y  :", np.cumsum(y))
print(" Ravel of x   :", np.ravel(x))
print(" Ravel of y   :", np.ravel(y))

 Sum of x     : 150
 Sum of y     : 75
 Minimum of x : 10
 Minimum of y : 5
 Maximam of x : 50
 Maximam of y : 25
 Mean of x    : 30.0
 Mean of y    : 15.0
 std of x     : 14.142135623730951
 std of y     : 7.0710678118654755
 Cumsum of x  : [ 10  30  60 100 150]
 Cumsum of y  : [ 5 15 30 50 75]
 Ravel of x   : [10 20 30 40 50]
 Ravel of y   : [ 5 10 15 20 25]


In [236]:
print(np.transpose(x))

[10 20 30 40 50]


In [242]:
print(np.delete(x,[2]))

[10 20 40 50]


In [246]:
print(np.append(x,60))

[10 20 30 40 50 60]


In [247]:
print(np.insert(x,0,100))

[100  10  20  30  40  50]


In [256]:
list1=[50,10,20,40,80]
list2=[70,78,79,45,12]
list3=[12,45,25,78,65]
a=np.array((list1+list2+list3)).reshape(3,5)
print(a)

[[50 10 20 40 80]
 [70 78 79 45 12]
 [12 45 25 78 65]]


In [257]:
a[::-1]

array([[12, 45, 25, 78, 65],
       [70, 78, 79, 45, 12],
       [50, 10, 20, 40, 80]])

In [261]:
a[:,4]

array([80, 12, 65])

In [293]:
a[-1][5::-1]

array([65, 78, 25, 45, 12])

## Pandas

In [87]:
import pandas as pd

In [88]:
a=[1,2,3,4,5]
data=pd.Series(a)
print(data)
print("--------------One Deminention------------------")
data=pd.Series((1,2,3,4),index=["a","b","c","d"])
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64
--------------One Deminention------------------
a    1
b    2
c    3
d    4
dtype: int64


In [89]:
data[1]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24964\3862107824.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[1]


2

In [90]:
data[3]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24964\977688468.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[3]


4

In [91]:
data[2]=33
data[3]=44
print(data)

a     1
b     2
c    33
d    44
dtype: int64


C:\Users\ASUS\AppData\Local\Temp\ipykernel_24964\2297278332.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  data[2]=33
C:\Users\ASUS\AppData\Local\Temp\ipykernel_24964\2297278332.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  data[3]=44


In [92]:
print(len(data))
print(type(data))
print(data.shape)
print(data.size)
print(data.dtype)

4
<class 'pandas.core.series.Series'>
(4,)
4
int64


In [173]:
info={"name":["abhishek","shanker","suresh","aniket","vitthal"],#two dimention
      "roll no":[10,45,25,45,36],
      "laptop":["yes","yes","no","no","no"],
      "city":["Benglore","pune","ratnagiri","aurangabd","london"]}

In [174]:
data=pd.DataFrame(info)
data

name  roll no laptop       city
0  abhishek       10    yes   Benglore
1   shanker       45    yes       pune
2    suresh       25     no  ratnagiri
3    aniket       45     no  aurangabd
4   vitthal       36     no     london

In [175]:
data[::-1]

name  roll no laptop       city
4   vitthal       36     no     london
3    aniket       45     no  aurangabd
2    suresh       25     no  ratnagiri
1   shanker       45    yes       pune
0  abhishek       10    yes   Benglore

In [176]:
data[0:5:2]

name  roll no laptop       city
0  abhishek       10    yes   Benglore
2    suresh       25     no  ratnagiri
4   vitthal       36     no     london

In [177]:
data[:-1:]

name  roll no laptop       city
0  abhishek       10    yes   Benglore
1   shanker       45    yes       pune
2    suresh       25     no  ratnagiri
3    aniket       45     no  aurangabd

In [178]:
data.loc[0:0]

name  roll no laptop      city
0  abhishek       10    yes  Benglore

In [179]:
data.loc[0:2]

name  roll no laptop       city
0  abhishek       10    yes   Benglore
1   shanker       45    yes       pune
2    suresh       25     no  ratnagiri

In [180]:
data.iloc[0][0:3]

name       abhishek
roll no          10
laptop          yes
Name: 0, dtype: object

In [181]:
data.iloc[0,3]

'Benglore'

In [182]:
data.iloc[1,3]

'pune'

In [183]:
data.iloc[4,0]

'vitthal'

In [184]:
data[["name"]]

name
0  abhishek
1   shanker
2    suresh
3    aniket
4   vitthal

In [185]:
data[["city"]]

city
0   Benglore
1       pune
2  ratnagiri
3  aurangabd
4     london

In [186]:
data.iloc[0,3]="Banglore"
data.iloc[1,3]="Pune"
data.iloc[2,3]="Rantnagiri"
data.iloc[3,3]="Aurangabad"
data.iloc[4,3]="London"
data.iloc[0,0]="Abhishek dighule"
data.iloc[1,0]="Shankar pande"
data.iloc[2,0]="Suresh dighule"
data.iloc[3,0]="Aniket akolkar"
data.iloc[4,0]="Vitthal dighule"

In [187]:
data

name  roll no laptop        city
0  Abhishek dighule       10    yes    Banglore
1     Shankar pande       45    yes        Pune
2    Suresh dighule       25     no  Rantnagiri
3    Aniket akolkar       45     no  Aurangabad
4   Vitthal dighule       36     no      London

In [188]:
data.rename(columns={"name":"Name","roll no":"Roll NO","laptop":"Laptop","city":"City"},inplace=True)

In [189]:
data["Mobile"]="Redmi"

In [190]:
data.iloc[2,4]="Apple"
data.iloc[3,4]="Samsung"
data.iloc[4,4]="No Mobile"

In [191]:
data

Name  Roll NO Laptop        City     Mobile
0  Abhishek dighule       10    yes    Banglore      Redmi
1     Shankar pande       45    yes        Pune      Redmi
2    Suresh dighule       25     no  Rantnagiri      Apple
3    Aniket akolkar       45     no  Aurangabad    Samsung
4   Vitthal dighule       36     no      London  No Mobile

In [192]:
data[["Name","Mobile"]]#Columns

Name     Mobile
0  Abhishek dighule      Redmi
1     Shankar pande      Redmi
2    Suresh dighule      Apple
3    Aniket akolkar    Samsung
4   Vitthal dighule  No Mobile

In [193]:
data["Mobile"].unique()

array(['Redmi', 'Apple', 'Samsung', 'No Mobile'], dtype=object)

In [194]:
data["Name"].unique()

array(['Abhishek dighule', 'Shankar pande', 'Suresh dighule',
       'Aniket akolkar', 'Vitthal dighule'], dtype=object)

In [195]:
data["Laptop"].value_counts()

Laptop
no     3
yes    2
Name: count, dtype: int64

In [196]:
data.head(2)

Name  Roll NO Laptop      City Mobile
0  Abhishek dighule       10    yes  Banglore  Redmi
1     Shankar pande       45    yes      Pune  Redmi

In [197]:
data.tail(2)

Name  Roll NO Laptop        City     Mobile
3   Aniket akolkar       45     no  Aurangabad    Samsung
4  Vitthal dighule       36     no      London  No Mobile

In [198]:
data.describe()

Roll NO
count   5.000000
mean   32.200000
std    14.889594
min    10.000000
25%    25.000000
50%    36.000000
75%    45.000000
max    45.000000

In [199]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     5 non-null      object
 1   Roll NO  5 non-null      int64 
 2   Laptop   5 non-null      object
 3   City     5 non-null      object
 4   Mobile   5 non-null      object
dtypes: int64(1), object(4)
memory usage: 328.0+ bytes


In [200]:
data.loc[data["Mobile"]=="Redmi"]

Name  Roll NO Laptop      City Mobile
0  Abhishek dighule       10    yes  Banglore  Redmi
1     Shankar pande       45    yes      Pune  Redmi

In [201]:
data.loc[data["Name"].str.startswith("A")]

Name  Roll NO Laptop        City   Mobile
0  Abhishek dighule       10    yes    Banglore    Redmi
3    Aniket akolkar       45     no  Aurangabad  Samsung

In [202]:
data.loc[data["Name"].str.endswith("e")]

Name  Roll NO Laptop        City     Mobile
0  Abhishek dighule       10    yes    Banglore      Redmi
1     Shankar pande       45    yes        Pune      Redmi
2    Suresh dighule       25     no  Rantnagiri      Apple
4   Vitthal dighule       36     no      London  No Mobile

In [203]:
data.loc[(data["Laptop"]=="yes")&(data["Name"].str.startswith("A"))]

Name  Roll NO Laptop      City Mobile
0  Abhishek dighule       10    yes  Banglore  Redmi

In [204]:
data

Name  Roll NO Laptop        City     Mobile
0  Abhishek dighule       10    yes    Banglore      Redmi
1     Shankar pande       45    yes        Pune      Redmi
2    Suresh dighule       25     no  Rantnagiri      Apple
3    Aniket akolkar       45     no  Aurangabad    Samsung
4   Vitthal dighule       36     no      London  No Mobile

In [205]:
data.rank()

Name  Roll NO  Laptop  City  Mobile
0   1.0      1.0     4.5   2.0     3.5
1   3.0      4.5     4.5   4.0     3.5
2   4.0      2.0     2.0   5.0     1.0
3   2.0      4.5     2.0   1.0     5.0
4   5.0      3.0     2.0   3.0     2.0

In [206]:
data.sort_values(by="Name")

Name  Roll NO Laptop        City     Mobile
0  Abhishek dighule       10    yes    Banglore      Redmi
3    Aniket akolkar       45     no  Aurangabad    Samsung
1     Shankar pande       45    yes        Pune      Redmi
2    Suresh dighule       25     no  Rantnagiri      Apple
4   Vitthal dighule       36     no      London  No Mobile

In [207]:
data.sort_values(by="City")

Name  Roll NO Laptop        City     Mobile
3    Aniket akolkar       45     no  Aurangabad    Samsung
0  Abhishek dighule       10    yes    Banglore      Redmi
4   Vitthal dighule       36     no      London  No Mobile
1     Shankar pande       45    yes        Pune      Redmi
2    Suresh dighule       25     no  Rantnagiri      Apple

In [208]:
data.sort_values(by="Mobile")

Name  Roll NO Laptop        City     Mobile
2    Suresh dighule       25     no  Rantnagiri      Apple
4   Vitthal dighule       36     no      London  No Mobile
0  Abhishek dighule       10    yes    Banglore      Redmi
1     Shankar pande       45    yes        Pune      Redmi
3    Aniket akolkar       45     no  Aurangabad    Samsung

In [209]:
data

Name  Roll NO Laptop        City     Mobile
0  Abhishek dighule       10    yes    Banglore      Redmi
1     Shankar pande       45    yes        Pune      Redmi
2    Suresh dighule       25     no  Rantnagiri      Apple
3    Aniket akolkar       45     no  Aurangabad    Samsung
4   Vitthal dighule       36     no      London  No Mobile

In [210]:
len("Aniket akolkar")

14

In [211]:
data.drop(4,axis=0,inplace=True
         )

In [212]:
data

Name  Roll NO Laptop        City   Mobile
0  Abhishek dighule       10    yes    Banglore    Redmi
1     Shankar pande       45    yes        Pune    Redmi
2    Suresh dighule       25     no  Rantnagiri    Apple
3    Aniket akolkar       45     no  Aurangabad  Samsung

In [213]:
info1={"Name":["Vitthal","Sadhana","Yeshraj","Rohit","Rushi"],
       "Roll NO":[12,45,32,45,25],
       "Laptop":["Yes","Yes","No","Yes","No"],
       "Mobile":["Redmi","Oppo","Iphone","Vivo","oneplus"],
       "City" :["Delhi","Kolhapur","Mumbai","Pune","Aurangabd"]
}

In [214]:
data1=pd.DataFrame(info1)

In [215]:
data1

Name  Roll NO Laptop   Mobile       City
0  Vitthal       12    Yes    Redmi      Delhi
1  Sadhana       45    Yes     Oppo   Kolhapur
2  Yeshraj       32     No   Iphone     Mumbai
3    Rohit       45    Yes     Vivo       Pune
4    Rushi       25     No  oneplus  Aurangabd

In [139]:
a=pd.concat([data,data1],axis=0)

In [140]:
a

Name  Roll NO Laptop        City   Mobile
0  Abhishek dighule       10    yes    Banglore    Redmi
1     Shankar pande       45    yes        Pune    Redmi
2    Suresh dighule       25     no  Rantnagiri    Apple
3    Aniket akolkar       45     no  Aurangabad  Samsung
0           Vitthal       12    Yes       Delhi    Redmi
1           Sadhana       45    Yes    Kolhapur     Oppo
2           Yeshraj       32     No      Mumbai   Iphone
3             Rohit       45    Yes        Pune     Vivo
4             Rushi       25     No   Aurangabd  oneplus

In [141]:
a.sort_values(by="Name")

Name  Roll NO Laptop        City   Mobile
0  Abhishek dighule       10    yes    Banglore    Redmi
3    Aniket akolkar       45     no  Aurangabad  Samsung
3             Rohit       45    Yes        Pune     Vivo
4             Rushi       25     No   Aurangabd  oneplus
1           Sadhana       45    Yes    Kolhapur     Oppo
1     Shankar pande       45    yes        Pune    Redmi
2    Suresh dighule       25     no  Rantnagiri    Apple
0           Vitthal       12    Yes       Delhi    Redmi
2           Yeshraj       32     No      Mumbai   Iphone

In [142]:
data=pd.Series((1,2,3,4,5,6))
print(data)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [143]:
data[2]
data[3]

4

In [144]:
data[3]=40
data[4]=50

In [145]:
data

0     1
1     2
2     3
3    40
4    50
5     6
dtype: int64

In [146]:
for i in data:
    print(i)

1
2
3
40
50
6


In [147]:
print(type(data))
print(len(data))
print(data.dtype)
print(data.shape)
print(data.shape)

<class 'pandas.core.series.Series'>
6
int64
(6,)
(6,)


In [148]:
info={"name":["Abhishek","shankar","rohit","aniket","shanker"],
     "roll no":[10,20,30,40,50],
     "country ":["indian","pakistan","usa","isril","iran"]}

In [149]:
data=pd.DataFrame(info)

In [150]:
data

name  roll no  country 
0  Abhishek       10    indian
1   shankar       20  pakistan
2     rohit       30       usa
3    aniket       40     isril
4   shanker       50      iran

In [151]:
data.loc[0:0]

name  roll no country 
0  Abhishek       10   indian

In [152]:
data.loc[0 :2]

name  roll no  country 
0  Abhishek       10    indian
1   shankar       20  pakistan
2     rohit       30       usa

In [153]:
data[["name"]]

name
0  Abhishek
1   shankar
2     rohit
3    aniket
4   shanker

In [154]:
data[["roll no"]]

roll no
0       10
1       20
2       30
3       40
4       50

In [155]:
data.iloc[2,0]="ROHIT PAWAR"

In [156]:
data.iloc[2,0]

'ROHIT PAWAR'

In [157]:
data.rename(columns={"name":"NAME","roll no":"ROLL NO","country":"COUNTRY"},inplace=True)

In [158]:
data.sort_values(by="NAME")

NAME  ROLL NO  country 
0     Abhishek       10    indian
2  ROHIT PAWAR       30       usa
3       aniket       40     isril
1      shankar       20  pakistan
4      shanker       50      iran

In [168]:
data

NAME  ROLL NO  country 
0     Abhishek       10    indian
1      shankar       20  pakistan
2  ROHIT PAWAR       30       usa
3       aniket       40     isril
4      shanker       50      iran

In [164]:
print(data.shape)
print(data.size)
print(type(data))
print(len(data))

(5, 3)
15
<class 'pandas.core.frame.DataFrame'>
5


In [165]:
data.count()

NAME        5
ROLL NO     5
country     5
dtype: int64

In [167]:
data.sum()

NAME        AbhishekshankarROHIT PAWARaniketshanker
ROLL NO                                         150
country                  indianpakistanusaisriliran
dtype: object